### ISSUE TITLE
pytorch version requirement

### ISSUE THREAD

**Issue by johnyojohn** [EdwardDali/erag#1]
Hello, I ran into this error while installing the requirements.txt. 

OS: Ubuntu (WSL)
Python version: 3.11.8

Steps to reproduce:
git clone https://github.com/EdwardDali/erag.git && cd erag
pip install -r requirements.txt

Result:
ERROR: Could not find a version that satisfies the requirement torch==2.1.1 (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0)
ERROR: No matching distribution found for torch==2.1.1

Excited to try this project once I can get it running!

**Comment by EduardTalianu** [comment]
Hi,

Unfortunately the requirements file is altmost never updated correctly as I am adding new features constantly.
I recommend using Windows 10, it's the only system tested on so far.
If you stil want to use ubuntu wsl here are some options: 
**Update the requirements.txt file:**
You could try updating the PyTorch version in the requirements.txt file to a more recent version that's compatible with your system.
Replace the line torch==2.1.1 with torch==2.4.0 (or the latest version available) in the requirements.txt file.
Use a different Python version:
PyTorch 2.1.1 might not be compatible with Python 3.11. You could try using an earlier version of Python, such as 3.9 or 3.10.
**Install PyTorch separately:**
You can try installing PyTorch separately using the command provided on the official PyTorch website (https://pytorch.org/get-started/locally/). Choose the appropriate options for your system (Linux, Pip, Python, and CPU).
**Create a virtual environment.**

**Comment by EduardTalianu** [comment]
updated the requirements to not show versions

**Comment by EduardTalianu** [comment]
shoud work no; torch is no longer user
